heat_template_version: 2014-10-16

description: >
  This is an example showing how you can do firstboot configuration
  of the nodes via cloud-init.  To enable this, replace the default
  mapping of OS::TripleO::NodeUserData in ../overcloud_resource_registry*

parameters:
  ComputeKernelArgs:
    description: >
      Space seprated list of Kernel args to be update to grub.
      The given args will be appended to existing args of GRUB_CMDLINE_LINUX in file /etc/default/grub
      Example: "intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=1"
    type: string
    default: ""
  ComputeHostnameFormat:
    type: string
    default: ""
  HostCpusList:
    description: >
      A list or range of physical CPU cores to be tuned.
      The given args will be appended to the tuned cpu-partitioning profile.
      Ex. HostCpusList: '4-12' will tune cores from 4-12
    type: string
    default: ""

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: boot_config}
      - config: {get_resource: compute_kernel_args}

  boot_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        yum_repos:
          # Overcloud images deployed without any repos.
          # In order to install required tuned profile an activate it, we should create FDP repo.
          rhelosp-rhel-7-fast-datapth:
            name: Fast Datapath packages
            baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/fast-datapath/os/
            enabled: true
            gpgcheck: false
          rhel-7-common:
            name: RHEL 7 Common
            baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/$basearch/rh-common/os/
            enabled: 1
            gpgcheck: 0
          red-hat-enterprise-linux:
            name: Red Hat Enterprise Linux $releasever - $basearch - Server
            baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os/
            enabled: 1
            gpgcheck: 0

  # Verify the logs on /var/log/cloud-init.log on the overcloud node
  compute_kernel_args:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -x
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDs8Y0lzJJmyWE8VSOyEbMMpRkVkw9A+JwZ3yRqNHBXkvUDEdeYL0vUXgEBK+t1cirhuer6yoJuNkpggVv8rVZHSxy6FZI5+TFEv4lzb7bgBaJPXj4avFXWR66K06EAah7wsATGo1F169jY2DSJO+HetK2HIb4NX7gHZMcdUUcPedD7muT6T7HnItNK4vH93lwD8/AY9+14C3j7StkTmtJmWCElYgI0Y1bQamunHjEVCVKUnYq+1yozo+C09nlJEPRspaWa4qrFlg1wT3FMzPOVxi2gGRbHmRFkmmqHu2UYTbXDRDqMIqEFhhdbVVIGhueNqD1iIK1qF99HnGX8pKUF stack@perf98.perf.lab.eng.bos.redhat.com" > /root/.ssh/authorized_keys
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCjMJ7ty4hS8T6NSdKhTtxIF0nMejChxC48c7dyIJTBtfgH9V01JJZl8SqMmja7zwdQOSs9z3gMHXnqwst1qW1k4FpK9inwsoLwjPfRHQq5QHXaYQW0rn3Oj34gY+X5BSDneA5KkvgldxGkgMG4lJDjkAmqza9b9dCNqhxDuW70Cw== root@perf98.perf.lab.eng.bos.redhat.com" >> /root/.ssh/authorized_keys
            FORMAT=$COMPUTE_HOSTNAME_FORMAT
            if [[ -z $FORMAT ]] ; then
              FORMAT="compute" ;
            else
              # Assumption: only %index% and %stackname% are the variables in Host name format
              FORMAT=$(echo $FORMAT | sed  's/\%index\%//g' | sed 's/\%stackname\%//g') ;
            fi
            if [[ $(hostname) == *$FORMAT* ]] ; then
              # Install the tuned package
              yum install -y tuned-profiles-cpu-partitioning

              tuned_conf_path="/etc/tuned/cpu-partitioning-variables.conf"
              echo "isolated_cores=2" > $tuned_conf_path
              tuned-adm profile cpu-partitioning
              if [ -n "$TUNED_CORES" ]; then
                grep -q "^isolated_cores" $tuned_conf_path
                if [ "$?" -eq 0 ]; then
                  sed -i 's/^isolated_cores=.*/isolated_cores=$TUNED_CORES/' $tuned_conf_path
                else
                  echo "isolated_cores=$TUNED_CORES" >> $tuned_conf_path
                fi
                tuned-adm profile cpu-partitioning
              fi

              sed 's/^\(GRUB_CMDLINE_LINUX=".*\)"/\1 $KERNEL_ARGS isolcpus=$TUNED_CORES"/g' -i /etc/default/grub ;
              grub2-mkconfig -o /etc/grub2.cfg

            fi
            reboot
          params:
            $KERNEL_ARGS: {get_param: ComputeKernelArgs}
            $COMPUTE_HOSTNAME_FORMAT: {get_param: ComputeHostnameFormat}
            $TUNED_CORES: {get_param: HostCpusList}

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
